### ISSUE TITLE
Limitations about ROS drivers for KUKA iiwa robot

### ISSUE THREAD

**Issue by jacknlliu** [jacknlliu/development-issues#46]
> The current interface for real-time control is called in the new Sunrise controller: `Connectivity`.
> This one is divided to 2 main packages : 
> -  **Soft** real-time control (2ms --> 20 ms): `Connectivity.SmartServo` (used by [IFL-CAMP/iiwa_stack](https://github.com/IFL-CAMP/iiwa_stack))
> - **Hard** real-time control (1ms --> 4ms ): `Connectivity.FRI` 2.0 (Successor of `FRI` 1.0) will be there from November 2014 onward. (used by [ahundt/grl](https://github.com/ahundt/grl.git), and [kuka-isir/lwr_hardware](https://github.com/kuka-isir/lwr_hardware/tree/7c67fdec47a0199451431c12af5848b2c84b78fb))
> —— From [Kuka LBR iiwa - Realtime Control Interface](https://www.robot-forum.com/robotforum/kuka-robot-forum/kuka-lbr-iiwa-realtime-control-interface/)

## Reference
- [Kuka LBR iiwa - Realtime Control Interface ](https://www.robot-forum.com/robotforum/kuka-robot-forum/kuka-lbr-iiwa-realtime-control-interface/)
- [Stop using the KONI Ethernet interface #7](https://github.com/IFL-CAMP/iiwa_stack/issues/7)
- [collaboration with grl #1](https://github.com/IFL-CAMP/iiwa_stack/issues/1)
- [Position Control using ROS #152](https://github.com/ahundt/grl/issues/152)
- V. Chawda and G. Niemeyer, “Toward torque control of a KUKA LBR IIWA for physical human-robot interaction,” in 2017 IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS), 2017, pp. 6387–6392.
- [Sending command/JointTorque to the robot #47](https://github.com/IFL-CAMP/iiwa_stack/issues/47)
- [kuka-isir/rtt_lwr](https://github.com/kuka-isir/rtt_lwr)
- [ahundt/grl - Implements soft real time arm drivers for Kuka LBR iiwa](https://github.com/ahundt/grl)
- [IFL-CAMP/iiwa_stack - ROS Indigo/Kinetic metapackage for the KUKA LBR IIWA R800/R820](https://github.com/IFL-CAMP/iiwa_stack)

**Comment by jacknlliu** [comment]
# motion too slow (iiwa stack)

It seems that effect of cartesian pose command is less than the joint position command in KUKA iiwa robot controller.

We can test something related with this.
- [x] parameterize  the `setMinimumTrajectoryExecutionTime` and  `setTimeoutAfterGoalReach`. We hope using a dynamic configuration for this.
- [x] script to test.
- [ ] using joint position and IK to replace the cartesian pose command.

## Reference
- [Not able to make iiwa_moveit work correctly on real Iiwa #99](https://github.com/IFL-CAMP/iiwa_stack/issues/99)
- [Moving the arm through a Cartesian pose trajectory using inverse kinematics and the joint trajectory action](http://wiki.ros.org/pr2_controllers/Tutorials/Moving%20the%20arm%20through%20a%20Cartesian%20pose%20trajectory)

**Comment by jacknlliu** [comment]
# wrong ttd (iiwa stack)

We use the `TimeToDestinationService` to get the time about the excutation, but the result seems not correct.

This caused that we can't use the cartesian pose command which needs determined time.

We need a script to test it.

**Comment by jacknlliu** [comment]
## TimeoutAfterGoalReach (iiwa stack)

Depending on our [iiwa_stack](https://github.com/jacknlliu/iiwa_stack/commit/b2db51f28fe4b1984be82a9ac9e0250c2bfbccff) version, when switching between different control modes, the `setTimeoutAfterGoalReach` will be called and then the controller will last such time to work. 

But if you just update the parameters of the current control mode, it will not work, because of the current [iiwa_stack implement](https://github.com/IFL-CAMP/iiwa_stack/blob/b9eb9429efda37d07643f1f5e532ed79ffa10169/iiwa_ros_java/src/de/tum/in/camp/kuka/ros/ROSSmartServo.java#L96). This will not call the `switchSmartServoMotion()` which creates a new motion with the `TimeoutAfterGoalReach` again.

**Comment by jacknlliu** [comment]
## Switching control modes caused exception (iiwa stack)

More details, see [iiwa_stack #120](https://github.com/IFL-CAMP/iiwa_stack/issues/120).

This is related with the safe operation in impedance mode and switching control mode. (The Law III of Asimov)

Possible solutions：

```java
import static com.kuka.roboticsAPI.motionModel.BasicMotions.positionHold;

// or
import com.kuka.roboticsAPI.motionModel.PositionHold;
```

In `iiwa_stack` [ROSMonitor.java](https://github.com/IFL-CAMP/iiwa_stack/blob/master/iiwa_ros_java/src/de/tum/in/camp/kuka/ros/ROSMonitor.java#L112), we know that we should update the commanded position to the current robot position.

```java
/*
    * Continuously updating the commanded position to the current robot
    * position If this is not done, when setting the stiffness back to
    * a high value the robot will go back to that position at full
    * speed: do not try that at home!!
    */
motion.getRuntime().setDestination(robot.getCurrentJointPosition());
```

**Temporay Solution:**
Please see https://github.com/jacknlliu/iiwa_stack/commit/dd35ef91c64c72fcdb08ee9798a46629caf424aa

### Reference
- [grl issues #99 - Swithing between interaction modes](https://github.com/ahundt/grl/issues/99)
- [grl issues #89 - Update current position after switching modes](https://github.com/ahundt/grl/issues/89)
- [exception when switching between position mode and impedance mode #120](https://github.com/IFL-CAMP/iiwa_stack/issues/120)
- [Workarounds include a brief hold position when switching between smart servo and cartesian impedance mode](https://github.com/ahundt/grl/releases/tag/v3.1.0)
- [PositionHold for compliant control mode](https://github.com/ahundt/grl/blob/b706970188e8f7e1de428dfc00266259e511f0c2/src/java/grl/src/grl/driver/GRL_Driver.java#L361)

**Comment by jacknlliu** [comment]
## Plan to use [grl](https://github.com/ahundt/grl) and [iiwa_stack](https://github.com/jacknlliu/iiwa_stack)

### Difference
- iiwa_stack is well documented, but some problems can't be solved by current version.
- grl uses the `FRI` interface, but iiwa_stack uses the `SmartServo` interface. 
- our sunrise os is 1.7, but the grl only support higher versions.

### Why?


### TODO
- [ ] give the stratification of the grl modules, we only need the lower modules.
- [ ] `catkinize` the grl modules what we need
- [ ] combined them

**Comment by jacknlliu** [comment]
## Teaching and Demonstration using KUKA LBR iiwa

- [HandGuiding mode](https://www.robot-forum.com/robotforum/kuka-lbr-iiwa/copy-teaching/)
- gravity compensation mode (joint impedance mode)

**Comment by jacknlliu** [comment]
## Control Robot with [kuka-isir/rtt_lwr](https://github.com/kuka-isir/rtt_lwr)



- [Simple joint position control in joint stiffness mode #8](https://github.com/kuka-isir/rtt_lwr/issues/8)
